export enum AppState {
  IDLE = "IDLE",
  CALCULATING = "CALCULATING",
  AWAITING_DRIVER = "AWAITING_DRIVER",
  DRIVER_EN_ROUTE = "DRIVER_EN_ROUTE",
  IN_PROGRESS = "IN_PROGRESS",
  PAYMENT_PENDING = "PAYMENT_PENDING",
  VERIFYING_PAYMENT = "VERIFYING_PAYMENT",
}

export enum CallStatus {
  NONE = "NONE",
  RINGING = "RINGING",
  CONNECTED = "CONNECTED",
  ENDED = "ENDED",
}
